services:
  portfolio:
    build:
      context: .
    image: nextjs-app
    container_name: portfolio
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
